name: Conditional Docker Build on PR Merge

on:
  pull_request:
    types: [closed]
    paths:
      - 'prod/**'
      - 'dev/**'

jobs:
  build-prod:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    name: Build Docker Image for Prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Prod Docker Image
        if: "contains(github.event.pull_request.head.repo.default_branch, 'prod/')"
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/prod-image:latest ./prod
          docker push "${{ secrets.DOCKER_USERNAME }}"/prod-image:latest
  build-dev:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    name: Build Docker Image for Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Dev Docker Image
        run: |
          if: "contains(github.event.pull_request.head.repo.default_branch, 'dev/')"
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/dev-image:latest ./dev
          docker push "${{ secrets.DOCKER_USERNAME }}"/dev-image:latest 
